version: '3'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    tty: true
    hostname: polytech_bot_1
    volumes:
      - "./:/app"
    env_file:
      - .env
    ports:
      - "3000:3000"

networks:
  default:
